services:
  - type: web
    name: inox-pharma-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://inox-pharma.onrender.com/api
      - key: VITE_SOCKET_URL
        value: https://inox-pharma.onrender.com